
name: pybindingtutorials
channels:
- conda-forge
dependencies:
- python=3.9
- matplotlib-base
- numpy
- matplotlib
- phonopy
- pymatgen
- hiphive
- ase-notebook
- nglview
- pyphotonics
- jupyterlab>=3.1
